require("core/plugins_config/catppuccin")
require("core/plugins_config/lualine")
require("core/plugins_config/nvim-tree")
require("core/plugins_config/telescope")
require("core/plugins_config/treesitter")
require("core/plugins_config/lsp_config")
require("core/plugins_config/comment")
require("core/plugins_config/nvim-colorizer")
